import React from "react"
import Layout from "../components/layout"
import Seo from "../components/seo"
import "../styles/colophon.css"

const ColophonPage: React.FC = () => {
  return (
    <Layout>
      <div className="colophon-page">
        <h1 className="colophon-page__title">Colophon</h1>
        <p className="colophon-page__intro">
          Details about how this site is built, the tools used, and transparency about AI usage.
        </p>

        {/* AI Use and Disclosure */}
        <section className="colophon-section">
          <h2 className="colophon-section__title">AI Use & Disclosure</h2>
          <p>
            This site uses AI in several ways. In the spirit of transparency, here's a full accounting:
          </p>

          <h3 className="colophon-subsection__title">Content Generation</h3>
          <p>
            Some articles on this blog are written by AI personas powered by Claude (Anthropic).
            These posts are clearly attributed to their respective persona authors in the article
            frontmatter. Human-written posts are attributed to "François" or have no author field.
          </p>

          <h3 id="personas" className="colophon-subsection__title">Personas</h3>
          <p>
            The following AI personas contribute content to this blog. Each has a distinct voice,
            background, and area of expertise:
          </p>
          <ul className="colophon-list colophon-list--personas">
            <li>
              <strong>Nora</strong> — Technical Writer & Cloud/AI Strategist. Former systems architect
              turned independent writer, she synthesizes complex technical trends into coherent narratives.
            </li>
            <li>
              <strong>Theo</strong> — Philosopher of Technology. Oxford PhD exploring how AI reshapes
              human agency and meaning, drawing on traditions from Aristotle to Illich.
            </li>
            <li>
              <strong>Eli</strong> — Principal Engineer & Language Tinkerer. Compiler enthusiast who
              writes about CS fundamentals, systems programming, and understanding computation from first principles.
            </li>
            <li>
              <strong>Jake</strong> — Senior Web Application Designer. 20 years in the SF design scene,
              bridging design and code with a focus on component systems and accessibility.
            </li>
          </ul>

          <h3 className="colophon-subsection__title">Audio Narration</h3>
          <p>
            Article audio is generated using <a href="https://elevenlabs.io" target="_blank" rel="noopener noreferrer">ElevenLabs</a> text-to-speech.
            The narration automatically skips code blocks, tables, and technical schemas to provide
            a better listening experience.
          </p>

          <h3 className="colophon-subsection__title">Semantic Search</h3>
          <p>
            The search functionality uses vector embeddings generated by the{" "}
            <a href="https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2" target="_blank" rel="noopener noreferrer">
              all-MiniLM-L6-v2
            </a>{" "}
            model via <a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noopener noreferrer">Transformers.js</a>.
            Embeddings are computed at build time, and the model runs entirely in your browser—no
            data is sent to external servers for search queries.
          </p>
        </section>

        {/* Tech Stack */}
        <section className="colophon-section">
          <h2 className="colophon-section__title">Tech Stack</h2>
          <ul className="colophon-list">
            <li>
              <strong>Framework:</strong>{" "}
              <a href="https://www.gatsbyjs.com/" target="_blank" rel="noopener noreferrer">Gatsby 5</a> (React-based static site generator)
            </li>
            <li>
              <strong>Language:</strong> TypeScript + JavaScript
            </li>
            <li>
              <strong>Styling:</strong> Plain CSS with custom properties (no frameworks)
            </li>
            <li>
              <strong>Content:</strong> Markdown with gatsby-transformer-remark
            </li>
            <li>
              <strong>Code Highlighting:</strong> PrismJS
            </li>
            <li>
              <strong>Hosting:</strong> GitHub Pages
            </li>
            <li>
              <strong>Development:</strong> Built with assistance from{" "}
              <a href="https://claude.ai/code" target="_blank" rel="noopener noreferrer">Claude Code</a>
            </li>
          </ul>
        </section>

        {/* Typography */}
        <section className="colophon-section">
          <h2 className="colophon-section__title">Typography</h2>
          <ul className="colophon-list">
            <li>
              <strong>Serif:</strong>{" "}
              <a href="https://github.com/niclib/Literata" target="_blank" rel="noopener noreferrer">Literata</a> —
              designed for long-form reading, used for body text and article content
            </li>
            <li>
              <strong>Sans-serif:</strong>{" "}
              <a href="https://rsms.me/inter/" target="_blank" rel="noopener noreferrer">Inter</a> —
              optimized for screens, used for UI elements, navigation, and metadata
            </li>
            <li>
              <strong>Monospace:</strong>{" "}
              <a href="https://github.com/tonsky/FiraCode" target="_blank" rel="noopener noreferrer">Fira Code</a> —
              with ligatures, for code blocks
            </li>
          </ul>
          <p>
            Type scale follows a modular ratio for visual harmony across headings and body text.
          </p>
        </section>

        {/* Credits & Inspiration */}
        <section className="colophon-section">
          <h2 className="colophon-section__title">Credits & Inspiration</h2>
          <p>
            Design inspired by the principle that good typography and generous whitespace
            make content more readable. The minimal aesthetic prioritizes content over chrome.
          </p>
          <p>
            Special thanks to the open source community for the tools that make this site possible,
            and to Anthropic for Claude, which assisted in both code and content creation.
          </p>
        </section>
      </div>
    </Layout>
  )
}

export const Head = () => <Seo title="Colophon" />

export default ColophonPage
